Homework 11 guisupov done
eugene-okulik/guisupov pull request #10
Opened 2024-12-01 10:17 UTC by guisupov

Женя, привет! это пока самое сложное задание с которым я залип )). В каждой задачке есть маленький подвох)), здесь для меня их было два: 
1. Борьба с запятой, если добавляется слово "зарезервирован", сначала искал, как победить методами строк, сдался, сделал как сделал )))
2. При инициализации второго класса, какую то часть времени матерился, когда is_reserved=False я пытался в середине вставить(скопировал от родительского класса, и просто добавлял атрибуты  дочернего)

раньше во время обучения никогда сильно не обращал, внимание на восклицательный знак справа в верху )))
сейчас он мой первый враг)) на форматирование потратил очень много времени ))
Из вопросов остались такие: 1. Правильно ли сделал перенос строк при выводе на печать, может есть какие то другие паттерны? 2. При создании объектов во втором классе атрибут название атрибута, явно прописывается, в родительском классе просто, как подсказки подсвечиваются. Можно просто ссылки, где про это почитать, возможно ты где то это подсвечивал, и я пропустил, можешь ткнуть носом))

2024-12-01 11:07 UTC, guisupov commented
Женя, можешь порекомендовать  плагины для пайчарма, которые бы проверяли на линтеры, ни одного задания не вернул без переделок)) Вот и очередной раз, пайчарм упорно говорил, что у меня все хорошо, по итогу получилось, что не очень)) пошел погуглил есть PyLint и Flale8 посоветуй пожалуйста в сторону какого посмотреть.

2024-12-01 11:40 UTC, eugene-okulik requested changes
Всё круто. Нужно только убрать повторение кода.

2024-12-01 11:40 UTC, eugene-okulik commented on homework/grigory_isupov/Homework_11/task_1.py
> +      f"материал: {school_book.page_material}{', зарезервирована' if school_book.is_reserved else ''}")
Само распечатывание и эту запятую хорошо победил. Но что плохо, так это то, что ты пвторяешь один и тот же код для каждой книги. А можно было сделать одну функцию, которая может распечатывать нужную книгу. А можно это даже сделать методом в классе.

2024-12-01 11:40 UTC, eugene-okulik commented on homework/grigory_isupov/Homework_11/task_1.py
> +      f"материал: {school_book.page_material}{', зарезервирована' if school_book.is_reserved else ''}")
Перенос ок. Ты использовал самый правильный подход.

2024-12-01 11:40 UTC, eugene-okulik commented on homework/grigory_isupov/Homework_11/task_1.py
> +)
Что-то я не очень понял на чем ты тут залип. Да, можно так, как ты сделал. Это очень наглядно и часто так и делают. А можно просто позиционно это сделать
```python
school_book_6 = SchoolBook("Алгебра", "Иванов", 200, "13: 978-2-266-11156-6", "Математика", 9)
```
Главное, указать всё в том же порядке, как у тебя в классе написано

2024-12-01 15:53 UTC, guisupov commented on homework/grigory_isupov/Homework_11/task_1.py
> +)
вот так пробовл is_reserved=False, передавать, просто скопировал, аргументы из родительского класса, и начал добавлять аргументы из дочернего ))
class SchoolBook(Books):
    def __init__(self, title, author, page_count, isbn, is_reserved=False, subject, class_room, has_exercises=False):
        super().__init__(title, author, page_count, isbn, is_reserved)

2024-12-02 06:53 UTC, eugene-okulik commented on homework/grigory_isupov/Homework_11/task_1.py
> +)
> вот так пробовл is_reserved=False, передавать, просто скопировал, аргументы из родительского класса, и начал добавлять аргументы из дочернего )) class SchoolBook(Books): def **init**(self, title, author, page_count, isbn, is_reserved=False, subject, class_room, has_exercises=False): super().**init**(title, author, page_count, isbn, is_reserved)

Ну, здесь у тебя про порядок аргументов. В видео про функции я рассказывал, что всегда должны идти сначала позиционные, потом именованные. Проще говоря, все, которые со знаком `=` должны идти в конце.

2024-12-02 06:56 UTC, eugene-okulik requested changes
Нужно поправить то, на что ругается линт

2024-12-02 06:56 UTC, eugene-okulik commented on homework/grigory_isupov/Homework_11/task_1.py
> +        )
:+1:

2024-12-02 06:56 UTC, eugene-okulik commented on homework/grigory_isupov/Homework_11/task_1.py
> +                + f", предмет: {self.subject}, класс: {self.class_room}"
Линт ругается на вот этот отступ. Отступ в питоне всегда 4 пробела от предыдущей строки, а здесь у тебя больше чем 4. Да, пайчарм поставил так автоматически, но это он постоянно такую подлянку делает.

2024-12-02 10:03 UTC, guisupov commented on homework/grigory_isupov/Homework_11/task_1.py
> +                + f", предмет: {self.subject}, класс: {self.class_room}"
Спасибо, поправил. Реально поправил, затем нажал ctr+alt+L и снова подстава от пайчарма.

2024-12-03 07:02 UTC, eugene-okulik commented
> Женя, можешь порекомендовать плагины для пайчарма, которые бы проверяли на линтеры, ни одного задания не вернул без переделок)) Вот и очередной раз, пайчарм упорно говорил, что у меня все хорошо, по итогу получилось, что не очень)) пошел погуглил есть PyLint и Flake8 посоветуй пожалуйста в сторону какого посмотреть.

И тот и тот хороши. На гитхабе я использую как раз flake8

2024-12-03 07:07 UTC, eugene-okulik approved these changes

2024-12-03 07:07 UTC, merged